name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create PEM key
        run: |
          echo "${{ secrets.AWS_PEM_KEY }}" > aws-key.pem
          chmod 600 aws-key.pem

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Add host to known_hosts
        run: |
          ssh-keyscan -H 3.90.103.160 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i aws-key.pem deploy.sh ubuntu@3.90.103.160:/home/ubuntu/deploy.sh
          ssh -i aws-key.pem ubuntu@3.90.103.160 "bash ~/deploy.sh"
